declare global {
	namespace NodeJS {
		interface ProcessEnv {
			// Project
			APP_PROJECT_NAME: string
			APP_PROJECT_STORE: string
			APP_PROJECT_STORE_LINK: string

			// Server
			APP_DEV_SERVER_PORT: string
			APP_PROD_SERVER_PORT: string

			// Routes
			APP_VIEWS_DIR: string
			APP_PAGES_DIR: string
			APP_PAGES_STYLES_DIR: string
			APP_PAGES_SCRIPTS_DIR: string
			APP_COMPONENTS_DIR: string

			APP_ASSETS_STYLES_DIR: string
			APP_ASSETS_SCRIPTS_DIR: string
			APP_ASSETS_SCRIPTS_VENDOR_DIR: string
			APP_ASSETS_IMAGES_DIR: string
			APP_ASSETD_FAVICON_DIR: string
			APP_ASSETS_SPRITE_DIR: string
			APP_ASSETS_FONTS_DIR: string

			APP_BUILD_DIRNAME: string
			APP_BUILD_PAGES_DIRNAME: string
			APP_BUILD_STYLES_DIRNAME: string
			APP_BUILD_SCRIPTS_DIRNAME: string
			APP_BUILD_SCRIPTS_VENDOR_DIRNAME: string
			APP_BUILD_IMAGES_DIRNAME: string
			APP_BUILD_FAVICON_DIRNAME: string
			APP_BUILD_FONTS_DIRNAME: string

			APP_SPRITE_FILENAME: string
			APP_COMPONENTS_CONFIG_FILENAME: string
			APP_STYLES_VARIABLES_PATH: string

			// Config
			APP_BUILD_MINIFY_STYLES: string
			APP_BUILD_MINIFY_SCRIPTS: string

			// Artisan
			ARTISAN_NAME: string
			ARTISAN_BASH_NAME: string
			ARTISAN_TEMPLATES_DIR: string
			ARTISAN_TEMPLATE_PUG_PAGE: string
			ARTISAN_TEMPLATE_SCSS_PAGE: string
			ARTISAN_TEMPLATE_JS_PAGE: string

			ARTISAN_TEMPLATE_PUG_COMPONENT: string
			ARTISAN_TEMPLATE_SCSS_COMPONENT: string
			ARTISAN_TEMPLATE_JS_COMPONENT: string

			// Artisan autoimport
			ARTISAN_COMPONENT_AUTOIMPORT: string
			ARTISAN_COMPONENT_AUTOIMPORT_ALL_GLOBAL: string
			ARTISAN_COMPONENT_AUTOIMPORT_PUG_PATH: string
			ARTISAN_COMPONENT_AUTOIMPORT_SCSS_PATH: string
			ARTISAN_COMPONENT_AUTOIMPORT_JS_PATH: string
		}
	}
}

export {}
